[package]
name = "rbacrab"
version = "0.0.2"
edition = "2024"
description = "Rust ğŸ¦€RBACğŸ¦€ library with some crabbyğŸ¦€ğŸ§™ macro magic! Not so blazingly fast yet, but has all ğŸš€ğŸš€ğŸš€ chances."
authors = [
    "Kirill Lebedev (https://github.com/klebed)", 
    ]
publish = false

[dependencies]
serde = {version = "1.0", features = ["serde_derive"]}
arc-swap = "1.8"